import { ContainerStyled } from '@/components/container/container.styles';
import Head from 'next/head';
import { Menu } from '@/components/menu/menu';
import { Wrapper } from '@/components/wrapper/wrapper';
import { Header } from '@/components/header/header';
import { Footer } from '@/components/footer/footer';

export const Container = ({ children }) => {
  return (
    <>
      <Head>
        <title>Valkov.xyz - Artem Valkov</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <ContainerStyled>
        <Header/>
        <Wrapper>
          <Menu/>
          {children}
        </Wrapper>
        <Footer/>
      </ContainerStyled>
    </>
  )
}