import { ContainerStyled } from '@/components/container/container.styles';
import { MenuLink } from '@/components/menu_link/menu_link';
import Head from 'next/head';

export const Container = ({ children }) => {
  return (
    <>
      <Head>
        <title>Valkov.xyz - Artem Valkov</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <ContainerStyled>
        {children}
      </ContainerStyled>
    </>
  )
}