import { ContainerStyled } from '@/components/container/layout.styles';
import Head from 'next/head';
import { Menu } from '@/components/menu/menu';
import { Wrapper } from '@/components/wrapper/wrapper';
import { Footer } from '@/components/footer/footer';
import { Content } from '@/components/content/content';
import Header from '@/components/header/header';
import { useState, useEffect } from 'react';
import Loadingscreen from '@/components/loadingscreen/loadingscreen';
import LoadingScreen from '@/components/loadingscreen/loadingscreen';

export const Layout = ({ children }) => {
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true);
  }, [])

  return (
    <>
      <Head>
        <title>Valkov.xyz - Artem Valkov</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <>
        {children}
      </>
    </>
  )
}